import { useEffect, useState } from "react"
import { Project } from "../types"
import { dummyGenerations } from "../ugc_assets/assets/assets"
import { Loader } from "lucide-react"
import ProjectCard from "../components/ProjectCard"

const Community = () => {
    const [projects , setProjects] = useState<Project[]>([])
    const [loading , setLoading] = useState(true)

    const fetchProjects = async ()=>{
        setTimeout(()=>{
            setProjects(dummyGenerations)
            setLoading(false)
        },1500) // Shorter timeout for snappier mock loading
    }

    useEffect(()=>{
        fetchProjects();
    },[]);
    
    if(loading){
        return (
            <div className="flex flex-col gap-4 items-center justify-center h-[70vh]">
                <Loader className="animate-spin h-12 w-12 text-lavender-500"/>
                <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Loading community designs...</p>
            </div>
        )
    }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 md:py-16">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12 md:mb-16">
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl font-display text-gradient">
                Community Creations
            </h1>
            <p className="mt-4 text-base md:text-lg text-gray-500 dark:text-gray-400 font-sans">
                Browse professional short-form video ads generated by our creative community using AI.
            </p>
        </div>

        {/* Masonry Layout */}
        <div className="columns-1 sm:columns-2 lg:columns-3 gap-6 [column-fill:_balance] w-full">
            {projects.map((project) => (
                <ProjectCard key={project.id} gen={project} setGeneration={setProjects} forCommnity={true} />
            ))}
        </div>
    </div>
  )
}   

export default Community